[[constraint]]
  branch = "master"
  name = "github.com/acsellers/inflections"

[[constraint]]
  branch = "master"
  name = "github.com/dchest/captcha"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  name = "github.com/huacnlee/timeago"
  version = "master"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.0.0"

[[constraint]]
  name = "github.com/qor/admin"
  version = "1.0.0"

[[constraint]]
  name = "github.com/qor/publish"
  version = "1.0.0"

[[constraint]]
  name = "github.com/qor/qor"
  version = "1.0.0"

[[constraint]]
  name = "github.com/qor/sorting"
  version = "1.0.0"

[[constraint]]
  name = "github.com/qor/validations"
  version = "1.0.0"

[[constraint]]
  name = "github.com/revel/modules"
  version = "0.17.0"

[[constraint]]
  name = "github.com/revel/revel"
  version = "0.17.1"

[[constraint]]
  name = "github.com/russross/blackfriday"
  version = "2.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/tuxychandru/pubsub"
